version: "3.3" # Docker version

# networks:
#   frontend: # nginx <--> client
#   backend: # nginx <--> server

services:
  server:
    stdin_open: true # needed to allow react-scripts to watch for changes
    volumes:
      - ./server:/server
    build:
      context: ./server # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    environment:
      PORT: 5000
      # MONGO_URI
    ports:
      - 5000:5000 # DON'T map the container port to user localhost, let nginx do it
    # networks:
    #   - backend

  client:
    stdin_open: true # needed to allow react-scripts to watch for changes
    build:
      context: ./client # where to look for Dockerfile
      dockerfile: Dockerfile.dev # what dockerfile
    volumes:
      - ./client:/client
    # environment:
    # PORT: 3000
    ports:
      - 3000:3000 # map the localhost 3000 -> 3000 # DON'T map the container port to user localhost, let nginx do it if we use nginx
    # networks:
    #   - frontend
#   nginx:
#     restart: always
#     build:
#       context: ./nginx # where to look for Dockerfile
#       dockerfile: Dockerfile # what dockerfile
#     ports:
#       - 3000:3000 # ONLY nginx map the host to  user localhost
#     networks:
#       - frontend
#       - backend
#     depends_on:
#       - client
#       - server
